### ISSUE TITLE
Pagination on the search results

### ISSUE THREAD

**Issue by gmathi** [gmathi/NovelLibrary#41]
Search Results limited to only the first 25 novels

**Comment by gmathi** [comment]
I was thinking of using the 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.java
or 
Create a own custom solution to it.

**Comment by aouerfelli** [comment]
I think it's easy enough to make a custom solution.
The URL has a query page parameter `pg` (ex. https://www.novelupdates.com/series-ranking/?rank=popmonth&pg=1). You keep track of the current page (initially at 0), load `pg + 1` on request, and increment it by 1 if it loads successfully.
To implement pagination, you add a scroll listener to `RecyclerView` that checks when to load more. As an example:
```kt
recycler_view.addOnScrollListener(object : RecyclerView.OnScrollListener() {
    override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
        if (!loading && scrolledToBottom(recyclerView)) {
            loadMore()
        }
    }

    private fun scrolledToBottom(recyclerView: RecyclerView): Boolean {
        return !recyclerView.canScrollVertically(1)
    }
})
```
The loading boolean ideally keeps track of whether or not a page is currently being loaded right now. You can also check for a threshold (instead of waiting for user to get to the bottom of the list), but this is just an example.
Anyways, that's my take on it. It's up to you to decide what you want to implement.
