### ISSUE TITLE
Reader mode pagination

### ISSUE THREAD

**Issue by beta-phenylethylamine** [gmathi/NovelLibrary#73]
Reader mode is really nice already, but it would be really nice if it were to act like an ebook reader and paginate the body of the chapter. If there were pages left in the chapter it would flip to the next page, and jf there weren't it would flip to the next chapter. 

Probably nontrivial because it would mean a change from having reader mode only execute within the context of the webpage to reformat (which is how i assume it currently works) to actually extracting the content and having the reader itself format it into pages, but it would be a substantial UX improvement imo

**Comment by beta-phenylethylamine** [comment]
This could also be done by having the body formatted into separate divs and having css rules to hide and show certain divs be injected by the reader itself probably, if there's concern over the switch from "still technically serving the page to the reader" and "scraping the page" (which could be considered unwelcome by site owners).

**Comment by gmathi** [comment]
Reader mode already does this. The pagination is a swipe instead of a vertical scroll. Try to swipe from the edge of the screen to bring up the reader menu on the right drawer. Turn on the Reader mode, and you will see a UI with the ability to do some real customization like day/night mode, font, size, e.t.c.

**Comment by beta-phenylethylamine** [comment]
Brilliant, thank you, I never realized it had pagination before!
